// Mocks generated by Mockito 5.4.4 from annotations
// in notes/test/data/repository/content_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:notes/data/services/interfaces/content_service.dart'
    as _i2;
import 'package:notes/data/services/interfaces/model/content/content_dto.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalContentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalContentService extends _i1.Mock
    implements _i2.ContentService {
  MockLocalContentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ContentDto>> getContents(String? noteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContents,
          [noteId],
        ),
        returnValue: _i3.Future<List<_i4.ContentDto>>.value(<_i4.ContentDto>[]),
      ) as _i3.Future<List<_i4.ContentDto>>);

  @override
  _i3.Future<_i4.ContentDto?> getContentById(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContentById,
          [contentId],
        ),
        returnValue: _i3.Future<_i4.ContentDto?>.value(),
      ) as _i3.Future<_i4.ContentDto?>);

  @override
  _i3.Future<_i4.ContentDto?> updateContent(
    String? contentId,
    _i4.ContentDto? contentDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContent,
          [
            contentId,
            contentDto,
          ],
        ),
        returnValue: _i3.Future<_i4.ContentDto?>.value(),
      ) as _i3.Future<_i4.ContentDto?>);

  @override
  _i3.Future<int> getContentsCount(String? noteId) => (super.noSuchMethod(
        Invocation.method(
          #getContentsCount,
          [noteId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> switchPositions(
    String? firstContentId,
    String? secondContentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #switchPositions,
          [
            firstContentId,
            secondContentId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
