// Mocks generated by Mockito 5.4.4 from annotations
// in notes/test/data/repository/image_content_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:notes/data/services/interfaces/image_content_service.dart'
    as _i5;
import 'package:notes/data/services/interfaces/image_file_service_interface.dart'
    as _i7;
import 'package:notes/data/services/interfaces/model/content/content_dto.dart'
    as _i3;
import 'package:notes/data/services/interfaces/model/content/types/image/imagecontent_dto.dart'
    as _i2;
import 'package:notes/data/services/interfaces/model/file/imagefile_dto.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeImagecontentDto_0 extends _i1.SmartFake
    implements _i2.ImagecontentDto {
  _FakeImagecontentDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContentDto_1 extends _i1.SmartFake implements _i3.ContentDto {
  _FakeContentDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImagefileDto_2 extends _i1.SmartFake implements _i4.ImagefileDto {
  _FakeImagefileDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ImageContentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageContentService extends _i1.Mock
    implements _i5.ImageContentService {
  MockImageContentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ImagecontentDto> createImageContent(
          _i2.ImagecontentDto? content) =>
      (super.noSuchMethod(
        Invocation.method(
          #createImageContent,
          [content],
        ),
        returnValue:
            _i6.Future<_i2.ImagecontentDto>.value(_FakeImagecontentDto_0(
          this,
          Invocation.method(
            #createImageContent,
            [content],
          ),
        )),
      ) as _i6.Future<_i2.ImagecontentDto>);

  @override
  _i6.Future<_i2.ImagecontentDto> updateImageContent(
    String? contentId,
    _i2.ImagecontentDto? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateImageContent,
          [
            contentId,
            content,
          ],
        ),
        returnValue:
            _i6.Future<_i2.ImagecontentDto>.value(_FakeImagecontentDto_0(
          this,
          Invocation.method(
            #updateImageContent,
            [
              contentId,
              content,
            ],
          ),
        )),
      ) as _i6.Future<_i2.ImagecontentDto>);

  @override
  _i6.Future<_i3.ContentDto> getContentById(
    String? noteId,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContentById,
          [
            noteId,
            id,
          ],
        ),
        returnValue: _i6.Future<_i3.ContentDto>.value(_FakeContentDto_1(
          this,
          Invocation.method(
            #getContentById,
            [
              noteId,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i3.ContentDto>);

  @override
  _i6.Future<List<_i3.ContentDto>> getContents(String? noteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContents,
          [noteId],
        ),
        returnValue: _i6.Future<List<_i3.ContentDto>>.value(<_i3.ContentDto>[]),
      ) as _i6.Future<List<_i3.ContentDto>>);

  @override
  _i6.Future<void> deleteTypedContent(
    String? noteId,
    String? contentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTypedContent,
          [
            noteId,
            contentId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ImageFileServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageFileServiceInterface extends _i1.Mock
    implements _i7.ImageFileServiceInterface {
  MockImageFileServiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.ImagefileDto> saveImage(_i4.ImagefileDto? image) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveImage,
          [image],
        ),
        returnValue: _i6.Future<_i4.ImagefileDto>.value(_FakeImagefileDto_2(
          this,
          Invocation.method(
            #saveImage,
            [image],
          ),
        )),
      ) as _i6.Future<_i4.ImagefileDto>);

  @override
  _i6.Future<bool> deleteImage(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #deleteImage,
          [fileName],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i4.ImagefileDto> substituteImage(
    String? fileName,
    _i4.ImagefileDto? newImage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #substituteImage,
          [
            fileName,
            newImage,
          ],
        ),
        returnValue: _i6.Future<_i4.ImagefileDto>.value(_FakeImagefileDto_2(
          this,
          Invocation.method(
            #substituteImage,
            [
              fileName,
              newImage,
            ],
          ),
        )),
      ) as _i6.Future<_i4.ImagefileDto>);

  @override
  _i6.Future<_i8.Uint8List> getImage(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #getImage,
          [fileName],
        ),
        returnValue: _i6.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
      ) as _i6.Future<_i8.Uint8List>);
}
