// Mocks generated by Mockito 5.4.4 from annotations
// in notes/test/data/repository/text_content_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:notes/data/services/interfaces/model/content/content_dto.dart'
    as _i3;
import 'package:notes/data/services/interfaces/model/content/types/text/textcontent_dto.dart'
    as _i2;
import 'package:notes/data/services/interfaces/text_content_service.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTextcontentDto_0 extends _i1.SmartFake
    implements _i2.TextcontentDto {
  _FakeTextcontentDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContentDto_1 extends _i1.SmartFake implements _i3.ContentDto {
  _FakeContentDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TextContentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextContentService extends _i1.Mock
    implements _i4.TextContentService {
  MockTextContentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.TextcontentDto> createTextContent(
          _i2.TextcontentDto? content) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTextContent,
          [content],
        ),
        returnValue: _i5.Future<_i2.TextcontentDto>.value(_FakeTextcontentDto_0(
          this,
          Invocation.method(
            #createTextContent,
            [content],
          ),
        )),
      ) as _i5.Future<_i2.TextcontentDto>);

  @override
  _i5.Future<_i2.TextcontentDto> updateTextContent(
    String? contentId,
    _i2.TextcontentDto? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTextContent,
          [
            contentId,
            content,
          ],
        ),
        returnValue: _i5.Future<_i2.TextcontentDto>.value(_FakeTextcontentDto_0(
          this,
          Invocation.method(
            #updateTextContent,
            [
              contentId,
              content,
            ],
          ),
        )),
      ) as _i5.Future<_i2.TextcontentDto>);

  @override
  _i5.Future<_i3.ContentDto> getContentById(
    String? noteId,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContentById,
          [
            noteId,
            id,
          ],
        ),
        returnValue: _i5.Future<_i3.ContentDto>.value(_FakeContentDto_1(
          this,
          Invocation.method(
            #getContentById,
            [
              noteId,
              id,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ContentDto>);

  @override
  _i5.Future<List<_i3.ContentDto>> getContents(String? noteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContents,
          [noteId],
        ),
        returnValue: _i5.Future<List<_i3.ContentDto>>.value(<_i3.ContentDto>[]),
      ) as _i5.Future<List<_i3.ContentDto>>);

  @override
  _i5.Future<void> deleteTypedContent(
    String? noteId,
    String? contentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTypedContent,
          [
            noteId,
            contentId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
